@startuml

title __APP's Class Diagram__\n

  package com.example.donski.leitner {
    class BuildConfig {
    }
  }
  

  package com.example.donski.leitner {
    package com.example.donski.leitner.database {
      package com.example.donski.leitner.database.DAO {
        class DeckDao_Impl {
        }
      }
    }
  }
  

  package com.example.donski.leitner {
    package com.example.donski.leitner.database {
      package com.example.donski.leitner.database.DAO {
        class DeckToSetDao_Impl {
        }
      }
    }
  }
  

  package com.example.donski.leitner {
    package com.example.donski.leitner.database {
      package com.example.donski.leitner.database.DAO {
        class FlashcardDao_Impl {
        }
      }
    }
  }
  

  package com.example.donski.leitner {
    package com.example.donski.leitner.database {
      class LeitnerDatabase_Impl {
      }
    }
  }
  

  package android.arch.persistence.room {
    class R {
    }
  }
  

  package android.support.transition {
    class R {
    }
  }
  

  package android.arch.lifecycle {
    package android.arch.lifecycle.livedata {
      package android.arch.lifecycle.livedata.core {
        class R {
        }
      }
    }
  }
  

  package android.support.mediacompat {
    class R {
    }
  }
  

  package android.support.graphics.drawable {
    class R {
    }
  }
  

  package com.example.donski.leitner {
    class R {
    }
  }
  

  package android.support.design {
    class R {
    }
  }
  

  package android.support.v7.recyclerview {
    class R {
    }
  }
  

  package android.arch.lifecycle {
    package android.arch.lifecycle.extensions {
      class R {
      }
    }
  }
  

  package android.arch.persistence.db {
    package android.arch.persistence.db.framework {
      class R {
      }
    }
  }
  

  package android.arch.lifecycle {
    class R {
    }
  }
  

  package android.arch.lifecycle {
    package android.arch.lifecycle.viewmodel {
      class R {
      }
    }
  }
  

  package android.support.v4 {
    class R {
    }
  }
  

  package android.support.coreui {
    class R {
    }
  }
  

  package android.support.coreutils {
    class R {
    }
  }
  

  package android.support.graphics.drawable {
    package android.support.graphics.drawable.animated {
      class R {
      }
    }
  }
  

  package android.arch.persistence.db {
    class R {
    }
  }
  

  package android.support.fragment {
    class R {
    }
  }
  

  package android.arch.core {
    class R {
    }
  }
  

  package android.support.compat {
    class R {
    }
  }
  

  package android.support.v7.appcompat {
    class R {
    }
  }
  

  package android.support.constraint {
    class R {
    }
  }
  

  package android.arch.lifecycle {
    package android.arch.lifecycle.livedata {
      class R {
      }
    }
  }
  

  package com.example.donski.leitner {
    package com.example.donski.leitner.database {
      package com.example.donski.leitner.database.DAO {
        class SetDao_Impl {
        }
      }
    }
  }
  

  DeckDao_Impl -up-|> DeckDao
  DeckToSetDao_Impl -up-|> DeckToSetDao
  FlashcardDao_Impl -up-|> FlashcardDao
  LeitnerDatabase_Impl -up-|> LeitnerDatabase
  SetDao_Impl -up-|> SetDao


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
